services:
  mcp-fin-memory:
    image: redis:7-alpine
    container_name: mcp-fin-memory-redis
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
      - mcp-fin-network
  
  mcp-fin-server:
    image: mcp-fin:1.1
    container_name: mcp-fin-server
    env_file:
      - .env
    volumes:
      - ./app:/mcp-fin/app
    depends_on:
      - mcp-fin-memory
    ports:
      - "8003:8000"
    networks:
      - mcp-fin-network
      - itapia-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  redis_data:
  
networks:
  mcp-fin-network:
    driver: bridge
    name: mcp-fin-network

  itapia-network:
    external: true
    name: itapia-network
      
    