services:
  mcp-fin-memory:
    image: redis:7-alpine
    container_name: mcp-fin-memory-redis
    restart: unless-stopped
    env_file: 
      - ./mcp_hosts/.env
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
      - mcp-fin-network

  mcp-vector-db:
    image: chromadb/chroma 
    container_name: mcp-chroma-db
    restart: unless-stopped
    env_file:
      - ./mcp_hosts/.env
    ports:
      - "8010:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
    networks:
      - mcp-fin-network

  yf-service:
    image: yf-service:1.0
    container_name: mcp-fin-yf
    env_file:
      - ./yf/.env
    volumes:
      - ./yf/app:/yf/app
    ports:
      - "8004:8000"
    networks:
      - mcp-fin-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  
  mcp-servers:
    image: mcp-fin-servers:1.0
    container_name: mcp-fin-servers
    env_file:
      - ./mcp_servers/.env
    volumes:
      - ./mcp_servers/app:/mcp-servers/app
      - ./mcp_servers/spec:/mcp-servers/spec
    depends_on:
      - mcp-fin-memory
    ports:
      - "8003:8000"
    networks:
      - mcp-fin-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  
  mcp-hosts:
    image: mcp-fin-hosts:1.0
    container_name: mcp-fin-hosts
    restart: unless-stopped
    env_file:
      - ./mcp_hosts/.env
    volumes:
      - ./mcp_hosts/app:/mcp-hosts/app
      - ./mcp_hosts/scripts:/mcp-hosts/scripts
      - mcp_hosts_hf_cache:/root/.cache/huggingface
    depends_on:
      - mcp-fin-memory
      - mcp-servers
      - mcp-vector-db
    ports:
      - "8005:8000"
    networks:
      - mcp-fin-network
      - itapia-network
    command: /mcp-hosts/entrypoint.sh

volumes:
  redis_data:
  chroma_data:
  mcp_hosts_hf_cache:
  
networks:
  mcp-fin-network:
    driver: bridge
    name: mcp-fin-network

  itapia-network:
    external: true
    name: itapia-network
      
    