# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-09-16T10:40:01+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')


class StockRealtimePrice(BaseModel):
    ticker: str = Field(..., title='Ticker')
    """
    Mã symbol của ticker
    """
    open: Optional[float] = Field(None, title='Open')
    """
    Giá mở cửa hôm nay
    """
    day_high: Optional[float] = Field(None, title='Day High')
    """
    Giá cao nhất trong ngày
    """
    day_low: Optional[float] = Field(None, title='Day Low')
    """
    Giá thấp nhất trong ngày
    """
    last_price: Optional[float] = Field(None, title='Last Price')
    """
    Giá tại thời điểm gọi API
    """
    last_volume: Optional[float] = Field(None, title='Last Volume')
    """
    Khối lượng giao dịch tại thời điểm gọi API
    """
    ts: int = Field(..., title='Ts')
    """
    Timestamp lúc mà trả kết quả
    """
    error: Optional[str] = Field(None, title='Error')
    """
    Thông báo lỗi nếu không lấy được dữ liệu
    """


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
